// cligen reads the OpenAPI spec and emits the command catalog under catalog/
// (`package catalog`: HelpEntries + TxShortcuts + the embedded spec.json). The
// catalog is the single generated artifact both interpreters walk at runtime —
// bron-cli's cobra tree and the desktop/CLI MCP tool layer.
//
// Resources come from OpenAPI tags (kebab-case), verbs are derived from the
// HTTP method + URL shape: GET /xxx → list, GET /xxx/{id} → get, POST → create,
// PUT/PATCH → update, DELETE → delete. Trailing path segments after an id become
// the verb (POST /xxx/{id}/yyy → yyy). Names map 1:1 with the spec — no aliases,
// no remapping — so the spec stays the source of truth and the catalog
// regenerates losslessly on every release.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// resourceAliases — short/disambiguated CLI names for select URL segments.
var resourceAliases = map[string]string{
	"address-book-records": "address-book",
	"addresses":            "deposit-addresses",
	"transactions":         "tx",
}

// endpointAliases — full (method,path) overrides for endpoints that logically
// belong under a different resource.
var endpointAliases = map[string]string{
	"GET /dictionary/asset-market-prices":  "assets prices",
	"GET /dictionary/symbol-market-prices": "symbols prices",
}

// httpMethods — keys under an OpenAPI path item that represent operations.
var httpMethods = map[string]struct{}{
	"get": {}, "post": {}, "put": {}, "patch": {},
	"delete": {}, "options": {}, "head": {}, "trace": {},
}

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintln(os.Stderr, "usage: cligen <openapi.json> <catalog-out-dir>")
		os.Exit(2)
	}
	specPath := os.Args[1]
	catalogDir := os.Args[2]

	data, err := os.ReadFile(specPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "read spec:", err)
		os.Exit(1)
	}

	var spec rawSpec
	if err := json.Unmarshal(data, &spec); err != nil {
		fmt.Fprintln(os.Stderr, "parse spec:", err)
		os.Exit(1)
	}

	plan, err := buildPlan(spec)
	if err != nil {
		fmt.Fprintln(os.Stderr, "build plan:", err)
		os.Exit(1)
	}
	sort.Slice(plan, func(i, j int) bool {
		if plan[i].Resource != plan[j].Resource {
			return plan[i].Resource < plan[j].Resource
		}
		return plan[i].Verb < plan[j].Verb
	})
	shortcuts := collectTxShortcuts(spec)

	if err := os.MkdirAll(catalogDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir catalog:", err)
		os.Exit(1)
	}
	helpSrc, err := emitHelpDoc(plan, shortcuts, "catalog")
	if err != nil {
		fmt.Fprintln(os.Stderr, "emit helpdoc:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(catalogDir, "helpdoc.go"), helpSrc, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write helpdoc.go:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(catalogDir, "spec.json"), data, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write spec.json:", err)
		os.Exit(1)
	}
	specSrc := []byte(`// Code generated by cligen. DO NOT EDIT.
package catalog

import _ "embed"

//go:embed spec.json
var Spec []byte
`)
	if err := os.WriteFile(filepath.Join(catalogDir, "spec.go"), specSrc, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write spec.go:", err)
		os.Exit(1)
	}

	fmt.Printf("generated %s (%d endpoints, %d tx-types)\n", catalogDir, len(plan), len(shortcuts))
}

// --- tx <type> shortcuts ---

type txShortcut struct {
	Key       string      // "withdrawal", "stake-delegation"
	Class     string      // "WithdrawalParams"
	TopFields []bodyField // CreateTransaction top-level fields except transactionType and params
	Params    []bodyField // leaves under "params." (without prefix)
}

// txKeyOverrides handles class→key mismatches the kebab-case derivation
// can't infer (e.g. "StakeUnDelegationParams" — the embedded "Un" capitals
// would split into "stake-un-delegation" instead of "stake-undelegation").
// Keep tiny; only add when a transactionType enum value disagrees with what
// classToKey would produce.
var txKeyOverrides = map[string]string{
	"StakeUnDelegationParams": "stake-undelegation",
}

func collectTxShortcuts(spec rawSpec) []txShortcut {
	reg := spec.Components.Schemas
	create, ok := reg["CreateTransaction"]
	if !ok {
		return nil
	}

	// Authoritative list of valid transactionType values (from the enum schema).
	// Shortcuts are only emitted for keys present in this set, so we never produce
	// a `bron tx <type>` that the API would reject.
	validTypes := map[string]bool{}
	if tt, ok := reg["TransactionType"]; ok {
		for _, v := range tt.Enum {
			if s, ok := v.(string); ok {
				validTypes[s] = true
			}
		}
	}

	// Collect top-level fields that are scalars/arrays — skip transactionType (fixed by shortcut)
	// and skip params (handled per shortcut below).
	topRequired := map[string]bool{}
	for _, r := range create.Required {
		topRequired[r] = true
	}
	var topFields []bodyField
	for name, prop := range create.Properties {
		if name == "transactionType" || name == "params" {
			continue
		}
		switch propKind(prop, reg) {
		case "scalar":
			t, f := leafTypeFormat(prop, reg)
			topFields = append(topFields, bodyField{DotPath: name, Required: topRequired[name], Type: t, Format: f, Description: strings.TrimSpace(prop.Description), Enum: enumValues(prop, reg)})
		case "array":
			t, f := arrayItemTypeFormat(prop, reg)
			topFields = append(topFields, bodyField{DotPath: name, Required: topRequired[name], Type: t + "[]", Format: f, Description: strings.TrimSpace(prop.Description), Enum: enumValues(prop, reg)})
		}
	}
	sort.Slice(topFields, func(i, j int) bool { return topFields[i].DotPath < topFields[j].DotPath })

	paramsProp, ok := create.Properties["params"]
	if !ok || len(paramsProp.OneOf) == 0 {
		return nil
	}

	seen := map[string]bool{}
	var out []txShortcut
	for _, p := range paramsProp.OneOf {
		if p.Ref == "" {
			continue
		}
		cls := refName(p.Ref)
		if seen[cls] {
			continue
		}
		seen[cls] = true

		key, ok := txKeyOverrides[cls]
		if !ok {
			key = classToKey(cls)
		}
		// Skip Params classes whose derived key isn't a real transactionType.
		// Avoids exposing dead `bron tx <type>` commands the API would reject.
		if len(validTypes) > 0 && !validTypes[key] {
			continue
		}

		out = append(out, txShortcut{
			Key:       key,
			Class:     cls,
			TopFields: topFields,
			Params:    collectLeaves(p, "", reg),
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Key < out[j].Key })
	return out
}

// classToKey converts a Params class name to its kebab-case TransactionType key.
// "WithdrawalParams" → "withdrawal"; "StakeDelegationParams" → "stake-delegation".
func classToKey(cls string) string {
	s := strings.TrimSuffix(cls, "Params")
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// --- spec types ---

type rawSpec struct {
	Paths      map[string]map[string]json.RawMessage `json:"paths"`
	Components struct {
		Schemas map[string]rawSchema `json:"schemas"`
	} `json:"components"`
}

type rawOp struct {
	Summary     string                 `json:"summary"`
	Description string                 `json:"description"`
	Tags        []string               `json:"tags"`
	Parameters  []rawParam             `json:"parameters"`
	RequestBody *rawReqBody            `json:"requestBody"`
	Responses   map[string]rawResponse `json:"responses"`
}

type rawResponse struct {
	Content map[string]rawContent `json:"content"`
}

type rawParam struct {
	Name        string     `json:"name"`
	In          string     `json:"in"`
	Required    bool       `json:"required"`
	Description string     `json:"description"`
	Schema      *rawSchema `json:"schema"`
}

type rawReqBody struct {
	Content map[string]rawContent `json:"content"`
}

type rawContent struct {
	Schema rawSchema `json:"schema"`
}

type rawSchema struct {
	Type        string               `json:"type"`
	Format      string               `json:"format"`
	Description string               `json:"description"`
	Ref         string               `json:"$ref"`
	Properties  map[string]rawSchema `json:"properties"`
	Required    []string             `json:"required"`
	Items       *rawSchema           `json:"items"`
	OneOf       []rawSchema          `json:"oneOf"`
	AnyOf       []rawSchema          `json:"anyOf"`
	AllOf       []rawSchema          `json:"allOf"`
	Enum        []interface{}        `json:"enum"`
}

// --- planning ---

type plannedCmd struct {
	Method      string
	Path        string
	Resource    string
	Verb        string
	Summary     string   // OpenAPI operation.summary, used as the cobra Short description
	PathArgs    []string // names from URL placeholders, in order
	QueryParams []param
	BodyFields  []bodyField // leaves of the request body schema (skips oneOf)
	HasBody     bool
	BodyRef     string   // component name of request body schema (e.g. "CreateTransaction")
	ResponseRef string   // component name of 200/201 response schema (e.g. "Transactions")
	Permissions []string // API key permissions allowed for this endpoint, e.g. ["View only", "Transaction Operator"]
}

// embedTokens picks the includeXxx query params and converts them to the
// kebab-case tokens accepted by the global `--embed` flag — gives the help
// renderer the per-command list of valid embed values without re-walking the
// raw query params at runtime.
func (c plannedCmd) embedTokens() []string {
	var out []string
	for _, q := range c.QueryParams {
		tok, ok := embedTokenFromInclude(q.Name)
		if !ok {
			continue
		}
		out = append(out, tok)
	}
	sort.Strings(out)
	return out
}

// parsePermissions extracts the API-key permission set from the operation
// description. The OpenAPI generator macro on the backend appends a line
// like `<sup>API Key permissions: View only, Transaction Operator, Full Access</sup>`
// to the description; we mine that line so the MCP server can use it as
// the source of truth for `--read-only` filtering (a tool ships in read-only
// mode iff its permission set is exactly {"View only"}).
//
// Returns nil if the description doesn't carry the marker — for endpoints
// without explicit permissions we treat them as state-changing (fail-safe).
var permissionsRe = regexp.MustCompile(`(?i)API Key permissions:\s*([^<\n]+)`)

func parsePermissions(description string) []string {
	m := permissionsRe.FindStringSubmatch(description)
	if len(m) < 2 {
		return nil
	}
	out := make([]string, 0, 4)
	for _, p := range strings.Split(m[1], ",") {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func embedTokenFromInclude(flag string) (string, bool) {
	const prefix = "include"
	if !strings.HasPrefix(flag, prefix) || len(flag) == len(prefix) {
		return "", false
	}
	rest := flag[len(prefix):]
	if rest[0] < 'A' || rest[0] > 'Z' {
		return "", false
	}
	var b strings.Builder
	for i, r := range rest {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String(), true
}

type param struct {
	Name        string
	Required    bool
	Type        string // OpenAPI type: "string" | "integer" | "boolean" | "array"
	Format      string // OpenAPI format: "int64" | "date-time-millis" | "decimal" | ...
	Description string
	Enum        []string // resolved enum values (for arrays: from items)
}

// bodyField is a body-schema leaf carrying its OpenAPI type/format/description.
// Type info drives the cobra flag's help string so users see the underlying shape
// (`[int64]`, `[date-time-millis]`, `[decimal]`) instead of a bare `string`.
type bodyField struct {
	DotPath     string
	Required    bool
	Type        string
	Format      string
	Description string
	Enum        []string
}

func buildPlan(spec rawSpec) ([]plannedCmd, error) {
	registry := spec.Components.Schemas

	var out []plannedCmd
	for route, methods := range spec.Paths {
		for key, raw := range methods {
			if _, ok := httpMethods[strings.ToLower(key)]; !ok {
				continue
			}
			var op rawOp
			if err := json.Unmarshal(raw, &op); err != nil {
				return nil, fmt.Errorf("path %q method %q: %w", route, key, err)
			}
			method := strings.ToUpper(key)
			cmd := derive(method, route)
			cmd.Summary = strings.TrimSpace(op.Summary)
			cmd.Permissions = parsePermissions(op.Description)
			for _, p := range op.Parameters {
				if p.In == "query" {
					qp := param{Name: p.Name, Required: p.Required, Description: strings.TrimSpace(p.Description)}
					if p.Schema != nil {
						qp.Type = p.Schema.Type
						qp.Format = p.Schema.Format
						if qp.Type == "array" && p.Schema.Items != nil && p.Schema.Items.Type != "" {
							qp.Type = p.Schema.Items.Type + "[]"
							if p.Schema.Items.Format != "" {
								qp.Format = p.Schema.Items.Format
							}
						}
						qp.Enum = enumValues(*p.Schema, registry)
					}
					cmd.QueryParams = append(cmd.QueryParams, qp)
				}
			}
			if op.RequestBody != nil {
				cmd.HasBody = true
				if jc, ok := op.RequestBody.Content["application/json"]; ok {
					cmd.BodyFields = collectLeaves(jc.Schema, "", registry)
					if jc.Schema.Ref != "" {
						cmd.BodyRef = refName(jc.Schema.Ref)
					}
				}
			}
			for _, code := range []string{"200", "201"} {
				if resp, ok := op.Responses[code]; ok {
					if jc, ok := resp.Content["application/json"]; ok && jc.Schema.Ref != "" {
						cmd.ResponseRef = refName(jc.Schema.Ref)
						break
					}
				}
			}
			out = append(out, cmd)
		}
	}
	return out, nil
}

// derive turns an (HTTP method, URL path) pair into a (resource, verb,
// pathArgs) triple. URL placeholders become arg names; trailing non-placeholder
// segments after an id become the verb. resourceAliases / endpointAliases
// override specific cases that don't read well from the URL alone.
func derive(method, path string) plannedCmd {
	if alias, ok := endpointAliases[method+" "+path]; ok {
		_, args := splitPath(path)
		return plannedCmd{Method: method, Path: path, Resource: firstWord(alias), Verb: tail(alias), PathArgs: args}
	}

	stripped := stripPrefix(path)
	segments := splitSegments(stripped)

	if len(segments) == 0 {
		return plannedCmd{Method: method, Path: path, Resource: "workspace", Verb: "info"}
	}

	resource := segments[0]
	if alias, ok := resourceAliases[resource]; ok {
		resource = alias
	}

	tailSeg := segments[1:]
	var ids []string
	var verbParts []string
	for _, s := range tailSeg {
		if isPlaceholder(s) {
			ids = append(ids, strings.TrimSuffix(strings.TrimPrefix(s, "{"), "}"))
		} else {
			verbParts = append(verbParts, s)
		}
	}

	verb := strings.Join(verbParts, " ")
	if verb == "" {
		switch method {
		case "GET":
			if len(ids) == 0 {
				verb = "list"
			} else {
				verb = "get"
			}
		case "POST":
			verb = "create"
		case "PUT", "PATCH":
			verb = "update"
		case "DELETE":
			verb = "delete"
		default:
			verb = strings.ToLower(method)
		}
	}
	return plannedCmd{Method: method, Path: path, Resource: resource, Verb: verb, PathArgs: ids}
}

var stripPrefixes = []string{"/workspaces/{workspaceId}", "/dictionary"}

func stripPrefix(p string) string {
	for _, pref := range stripPrefixes {
		if strings.HasPrefix(p, pref) {
			return strings.TrimPrefix(p, pref)
		}
	}
	return p
}

func splitSegments(p string) []string {
	parts := strings.Split(p, "/")
	out := parts[:0]
	for _, x := range parts {
		if x != "" {
			out = append(out, x)
		}
	}
	return out
}

func splitPath(p string) (string, []string) {
	stripped := stripPrefix(p)
	segs := splitSegments(stripped)
	var ids []string
	for _, s := range segs {
		if isPlaceholder(s) {
			ids = append(ids, strings.TrimSuffix(strings.TrimPrefix(s, "{"), "}"))
		}
	}
	return stripped, ids
}

func isPlaceholder(s string) bool {
	return len(s) >= 2 && s[0] == '{' && s[len(s)-1] == '}'
}

func firstWord(s string) string {
	i := strings.IndexByte(s, ' ')
	if i < 0 {
		return s
	}
	return s[:i]
}

func tail(s string) string {
	i := strings.IndexByte(s, ' ')
	if i < 0 {
		return ""
	}
	return s[i+1:]
}

// --- schema walking ---

// collectLeaves returns every scalar/array leaf reachable from schema, with the
// dot-path plus the leaf's OpenAPI type/format/description. Refs are resolved via
// registry. oneOf/anyOf branches are skipped (no discriminator, can't pick a
// shape). allOf is treated as union of properties.
func collectLeaves(s rawSchema, prefix string, reg map[string]rawSchema) []bodyField {
	var out []bodyField
	visited := map[string]bool{}
	walkLeaves(s, prefix, reg, visited, &out)
	sort.Slice(out, func(i, j int) bool { return out[i].DotPath < out[j].DotPath })
	return out
}

func walkLeaves(s rawSchema, prefix string, reg map[string]rawSchema, visited map[string]bool, out *[]bodyField) {
	if s.Ref != "" {
		name := refName(s.Ref)
		if visited[name] {
			return
		}
		visited[name] = true
		defer delete(visited, name)
		s = reg[name]
	}
	if len(s.OneOf) > 0 || len(s.AnyOf) > 0 {
		return
	}
	for _, child := range s.AllOf {
		walkLeaves(child, prefix, reg, visited, out)
	}
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	for name, prop := range s.Properties {
		dot := name
		if prefix != "" {
			dot = prefix + "." + name
		}
		switch propKind(prop, reg) {
		case "scalar":
			t, f := leafTypeFormat(prop, reg)
			*out = append(*out, bodyField{DotPath: dot, Required: required[name], Type: t, Format: f, Description: strings.TrimSpace(prop.Description), Enum: enumValues(prop, reg)})
		case "array":
			t, f := arrayItemTypeFormat(prop, reg)
			*out = append(*out, bodyField{DotPath: dot, Required: required[name], Type: t + "[]", Format: f, Description: strings.TrimSpace(prop.Description), Enum: enumValues(prop, reg)})
		case "object":
			walkLeaves(prop, dot, reg, visited, out)
		}
	}
}

// leafTypeFormat resolves a scalar property's (type, format), following $ref to
// pick up the underlying primitive (e.g. enum schemas surface as `string`).
func leafTypeFormat(s rawSchema, reg map[string]rawSchema) (string, string) {
	if s.Ref != "" {
		ref := reg[refName(s.Ref)]
		t := ref.Type
		if t == "" {
			t = "string"
		}
		return t, ref.Format
	}
	t := s.Type
	if t == "" {
		t = "string"
	}
	return t, s.Format
}

// arrayItemTypeFormat extracts the (item-type, item-format) for an array prop.
func arrayItemTypeFormat(s rawSchema, reg map[string]rawSchema) (string, string) {
	if s.Items == nil {
		return "string", ""
	}
	return leafTypeFormat(*s.Items, reg)
}

func propKind(s rawSchema, reg map[string]rawSchema) string {
	if s.Ref != "" {
		s = reg[refName(s.Ref)]
	}
	if len(s.OneOf) > 0 || len(s.AnyOf) > 0 {
		return "skip"
	}
	switch s.Type {
	case "string", "integer", "number", "boolean":
		return "scalar"
	case "array":
		return "array"
	case "object":
		return "object"
	}
	if len(s.Properties) > 0 {
		return "object"
	}
	return "scalar" // unknown → treat as scalar so user can still set it via --flag
}

func refName(ref string) string {
	parts := strings.Split(ref, "/")
	return parts[len(parts)-1]
}

// enumValues returns the enum string values reachable from s.
//
// For arrays, the enum lives on the items schema. For scalars, it may be
// inline (s.Enum) or behind a $ref to a named enum schema. Anything that
// resolves to non-string enum values is dropped — flag help only renders
// strings.
func enumValues(s rawSchema, reg map[string]rawSchema) []string {
	if s.Type == "array" && s.Items != nil {
		return enumValues(*s.Items, reg)
	}
	values := s.Enum
	if len(values) == 0 && s.Ref != "" {
		values = reg[refName(s.Ref)].Enum
	}
	if len(values) == 0 {
		return nil
	}
	out := make([]string, 0, len(values))
	for _, v := range values {
		if str, ok := v.(string); ok {
			out = append(out, str)
		}
	}
	return out
}

// --- emission ---

type resourceGroup struct {
	Name     string
	Commands []plannedCmd
}

func groupByResource(plan []plannedCmd) []resourceGroup {
	idx := map[string]int{}
	var groups []resourceGroup
	for _, c := range plan {
		i, ok := idx[c.Resource]
		if !ok {
			i = len(groups)
			idx[c.Resource] = i
			groups = append(groups, resourceGroup{Name: c.Resource})
		}
		groups[i].Commands = append(groups[i].Commands, c)
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i].Name < groups[j].Name })
	return groups
}

// emitHelpDoc generates the catalog file: the static HelpEntries / TxShortcuts
// maps the runtime cobra builder and the MCP tool layer both walk.
func emitHelpDoc(plan []plannedCmd, shortcuts []txShortcut, pkg string) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cligen. DO NOT EDIT.")
	fmt.Fprintf(&b, "package %s\n", pkg)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type HelpEntry struct {")
	fmt.Fprintln(&b, "\tMethod       string")
	fmt.Fprintln(&b, "\tPath         string")
	fmt.Fprintln(&b, "\tSummary      string // OpenAPI operation summary — cobra Short / CLI help one-liner")
	fmt.Fprintln(&b, "\tBodyRef      string")
	fmt.Fprintln(&b, "\tResponseRef  string")
	fmt.Fprintln(&b, "\tQueryParams  []HelpQueryParam")
	fmt.Fprintln(&b, "\tBodyFields   []HelpBodyField // request-body leaves (spec-derived), sans oneOf branches")
	fmt.Fprintln(&b, "\tPathArgs     []string")
	fmt.Fprintln(&b, "\tEmbedTokens  []string // valid --embed values, derived from includeXxx query params")
	fmt.Fprintln(&b, "\tPermissions  []string // API key permissions allowed, e.g. [\"View only\", \"Transaction Operator\"] — used by `bron mcp --read-only`")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type HelpQueryParam struct {")
	fmt.Fprintln(&b, "\tName        string")
	fmt.Fprintln(&b, "\tRequired    bool")
	fmt.Fprintln(&b, "\tType        string // OpenAPI type — \"string\" | \"integer\" | \"boolean\" | \"number\" | \"array\". \"string[]\" / \"integer[]\" for array of primitive.")
	fmt.Fprintln(&b, "\tFormat      string // OpenAPI format — \"int64\" | \"date-time-millis\" | \"decimal\" | ...")
	fmt.Fprintln(&b, "\tDescription string")
	fmt.Fprintln(&b, "\tEnum        []string")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type HelpBodyField struct {")
	fmt.Fprintln(&b, "\tDotPath     string // dot-path into the request body, e.g. \"networkFees.gasLimit\"")
	fmt.Fprintln(&b, "\tRequired    bool")
	fmt.Fprintln(&b, "\tType        string // OpenAPI type — \"string\" | \"integer\" | \"boolean\" | \"number\". \"string[]\" / \"integer[]\" for array of primitive.")
	fmt.Fprintln(&b, "\tFormat      string // OpenAPI format — \"int64\" | \"date-time-millis\" | \"decimal\" | ...")
	fmt.Fprintln(&b, "\tDescription string")
	fmt.Fprintln(&b, "\tEnum        []string")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type TxShortcut struct {")
	fmt.Fprintln(&b, "\tParamsRef    string")
	fmt.Fprintln(&b, "\tParams       []string")
	fmt.Fprintln(&b, "\tTopFields    []string")
	fmt.Fprintln(&b, "\tParamDefs    []HelpBodyField // params.* leaves (spec-derived), prefix stripped")
	fmt.Fprintln(&b, "\tTopFieldDefs []HelpBodyField // CreateTransaction top-level leaves shared by every shortcut")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "var HelpEntries = map[string]map[string]HelpEntry{")
	for _, g := range groupByResource(plan) {
		fmt.Fprintf(&b, "\t%q: {\n", g.Name)
		for _, c := range g.Commands {
			fmt.Fprintf(&b, "\t\t%q: {Method: %q, Path: %q, BodyRef: %q, ResponseRef: %q",
				c.Verb, c.Method, c.Path, c.BodyRef, c.ResponseRef)
			if c.Summary != "" {
				fmt.Fprintf(&b, ", Summary: %q", c.Summary)
			}
			if len(c.PathArgs) > 0 {
				fmt.Fprint(&b, ", PathArgs: []string{")
				for i, a := range c.PathArgs {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "%q", a)
				}
				fmt.Fprint(&b, "}")
			}
			if len(c.QueryParams) > 0 {
				fmt.Fprint(&b, ", QueryParams: []HelpQueryParam{")
				for i, q := range c.QueryParams {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "{Name: %q, Required: %t", q.Name, q.Required)
					if q.Type != "" {
						fmt.Fprintf(&b, ", Type: %q", q.Type)
					}
					if q.Format != "" {
						fmt.Fprintf(&b, ", Format: %q", q.Format)
					}
					if q.Description != "" {
						fmt.Fprintf(&b, ", Description: %q", q.Description)
					}
					if len(q.Enum) > 0 {
						fmt.Fprint(&b, ", Enum: []string{")
						for j, e := range q.Enum {
							if j > 0 {
								fmt.Fprint(&b, ", ")
							}
							fmt.Fprintf(&b, "%q", e)
						}
						fmt.Fprint(&b, "}")
					}
					fmt.Fprint(&b, "}")
				}
				fmt.Fprint(&b, "}")
			}
			if len(c.BodyFields) > 0 {
				fmt.Fprint(&b, ", BodyFields: ")
				emitHelpBodyFields(&b, c.BodyFields)
			}
			if tokens := c.embedTokens(); len(tokens) > 0 {
				fmt.Fprint(&b, ", EmbedTokens: []string{")
				for i, t := range tokens {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "%q", t)
				}
				fmt.Fprint(&b, "}")
			}
			if len(c.Permissions) > 0 {
				fmt.Fprint(&b, ", Permissions: []string{")
				for i, p := range c.Permissions {
					if i > 0 {
						fmt.Fprint(&b, ", ")
					}
					fmt.Fprintf(&b, "%q", p)
				}
				fmt.Fprint(&b, "}")
			}
			fmt.Fprintln(&b, "},")
		}
		fmt.Fprintln(&b, "\t},")
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "var TxShortcuts = map[string]TxShortcut{")
	for _, s := range shortcuts {
		fmt.Fprintf(&b, "\t%q: {ParamsRef: %q, ", s.Key, s.Class)
		fmt.Fprint(&b, "Params: []string{")
		for i, p := range s.Params {
			if i > 0 {
				fmt.Fprint(&b, ", ")
			}
			fmt.Fprintf(&b, "%q", p.DotPath)
		}
		fmt.Fprint(&b, "}, TopFields: []string{")
		for i, f := range s.TopFields {
			if i > 0 {
				fmt.Fprint(&b, ", ")
			}
			fmt.Fprintf(&b, "%q", f.DotPath)
		}
		fmt.Fprint(&b, "}")
		if len(s.Params) > 0 {
			fmt.Fprint(&b, ", ParamDefs: ")
			emitHelpBodyFields(&b, s.Params)
		}
		if len(s.TopFields) > 0 {
			fmt.Fprint(&b, ", TopFieldDefs: ")
			emitHelpBodyFields(&b, s.TopFields)
		}
		fmt.Fprintln(&b, "},")
	}
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("gofmt helpdoc: %w", err)
	}
	return formatted, nil
}

func emitHelpBodyFields(b *bytes.Buffer, fields []bodyField) {
	fmt.Fprint(b, "[]HelpBodyField{")
	for i, f := range fields {
		if i > 0 {
			fmt.Fprint(b, ", ")
		}
		fmt.Fprintf(b, "{DotPath: %q", f.DotPath)
		if f.Required {
			fmt.Fprint(b, ", Required: true")
		}
		if f.Type != "" {
			fmt.Fprintf(b, ", Type: %q", f.Type)
		}
		if f.Format != "" {
			fmt.Fprintf(b, ", Format: %q", f.Format)
		}
		if f.Description != "" {
			fmt.Fprintf(b, ", Description: %q", f.Description)
		}
		if len(f.Enum) > 0 {
			fmt.Fprint(b, ", Enum: []string{")
			for j, e := range f.Enum {
				if j > 0 {
					fmt.Fprint(b, ", ")
				}
				fmt.Fprintf(b, "%q", e)
			}
			fmt.Fprint(b, "}")
		}
		fmt.Fprint(b, "}")
	}
	fmt.Fprint(b, "}")
}
